### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by jiaoziqiang** [MoeXiaoHei/Yunzai-Bot-lite#1]
大佬能不能集成一下ffmpeg

还有就是chatgpt插件的地址改成原地址吧
镜像站无法访问了

**Comment by MoeXiaoHei** [comment]
@jiaoziqiang docker run -it -p 1022:22 -p 50832:50832 -p 3321:3321 --name yunzai registry.cn-hangzhou.aliyuncs.com/oicq/yunzai-bot-lite:latest
用这个镜像试一下

**Comment by jiaoziqiang** [comment]
OK完美镜像 好评好评😊😊👍
